### ISSUE TITLE
Gruntfile.js - SASS not compiling app.scss

### ISSUE THREAD

**Issue by 4Digits** [zurb/foundation-libsass-template#11]
Just cloned your repo to test the template.

When I run `grunt` (after installing the bower components of course), it gives me the following error:
```
Running "sass:dist" (sass) task
Warning: /var/www/html/foundation-libsass-template/scss/app.scss:1: error: file to import not found or unreadable: "settings"
 Use --force to continue.
```
Do the paths have to be changed in app.scss? Obviously it is not able to pull in the individuall scss-files.

**Comment by gakimball** [comment]
This is an older issue, but just to put it away, our CLI automatically copies the latest settings file from the Bower package when it creates a new project. However, this means if you just clone the repo and try to run it, it won't work because there's no settings file. So I added a placeholder file which an explanation of this.

As for the `!global` thing, it's since been resolved as of libsass 3.0.
